### ISSUE TITLE
Integration broken?

### ISSUE THREAD

**Issue by julianbenegas** [patrikholcak/now-dns#1]
I'm trying to run this integration, and the following error message gets displayed:

```
WARNING: Uh oh.

We encountered an error while trying to run this integration.

Integrations can error due to several reasons, including:

— Invalid JSX returned from the UI hook
— An improper API call
— Missing fields in the return body

Please contact the integration developer for help: Patrik Holčák (https://github.com/patrikholcak/now-dns).

You can share the following error with them:
WARNING: Failed to fetch
```

Is it me, or is it general?

**Comment by dohomi** [comment]
@julianbenegas I don't think the integration works at all. I'm receiving the same error on all DNS record updates.

**Comment by patrikholcak** [comment]
Hey everyone, I deployed a new version of the integration and it appears to be working correctly. Let me know if you have any problems
