### ISSUE TITLE
Error when saving a change

### ISSUE THREAD

**Issue by livelo-app** [patrikholcak/now-dns#3]
At any point when I make a change and attempt to save the change I come across this error:

Internal Integration Error
Reference Code: Nqrm1pAex4nESLpk5Cm8
Contact the Integration developer for more information.

I tested with simple TXT dns changes and still the same error.

**Comment by patrikholcak** [comment]
Hi, not sure why that would happen. Just tested it with TXT record in multiple browsers and it works. 🤷‍♂️

**Comment by mosqueradvd** [comment]
Hi. When I try to add a TXT record I get the same error as @livelo-app 

![dns-error](https://user-images.githubusercontent.com/46954736/82135561-c2c2fa00-97c9-11ea-97d2-5a689f3f3583.png)

**Comment by patrikholcak** [comment]
I’ll try to investigate and improve the error handling, when I have some time over the weekend.

**Comment by thexclu** [comment]
having this problem too while adding MX record

**Comment by patrikholcak** [comment]
Hey everyone, I just deployed a new version with basic error handling. This should give us a better understanding of what’s happening. Let me know what errors you encounter.

<img width="674" alt="Screenshot 2020-05-24 at 19 48 42" src="https://user-images.githubusercontent.com/72975/82760990-99bced80-9df7-11ea-8087-9445d80db5c8.png">

**Comment by mosqueradvd** [comment]
This is what comes up 🤔

![MX](https://user-images.githubusercontent.com/46954736/82772550-14403a00-9e05-11ea-8932-723513f57b8e.png)
![400](https://user-images.githubusercontent.com/46954736/82772559-1e623880-9e05-11ea-83d2-10fdaf958321.png)

**Comment by patrikholcak** [comment]
Might be an escaping thing, then. Let me take a look

**Comment by patrikholcak** [comment]
@mosqueradvd

Turns out if you want to reference the root domain, you just [leave the name blank](https://vercel.com/docs/api#endpoints/dns/create-a-new-dns-record/request-parameters). So I pushed a fix to replace `@` with empty string. Try now :)

**Comment by mosqueradvd** [comment]
@patrikholcak I tried it and now it works properly!!!!

Thank you very much 🔥

**Comment by patrikholcak** [comment]
🥳 closing this now. If any of you encounter another problem, please open new issue with the exact error message. Cheers!
